export const robots=[
    {
        id:1,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:2,
        name:"Aadil sayyed",
        username:'adisyd1',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:3,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:4,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:5,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:6,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },
    {
        id:7,
        name:"Aadil",
        username:'adisyd',
        email:"sayyedadil8552@gmail.com"
    },

]